# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: icp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='icp.proto',
  package='protoicp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ticp.proto\x12\x08protoicp\"\x19\n\tTransform\x12\x0c\n\x04vals\x18\x01 \x03(\x02\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"(\n\x05\x43loud\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.protoicp.Point\"/\n\x0cObjectClouds\x12\x1f\n\x06\x63louds\x18\x01 \x03(\x0b\x32\x0f.protoicp.Cloud2N\n\rCalcTransform\x12=\n\x0cgetTransform\x12\x16.protoicp.ObjectClouds\x1a\x13.protoicp.Transform\"\x00\x62\x06proto3'
)




_TRANSFORM = _descriptor.Descriptor(
  name='Transform',
  full_name='protoicp.Transform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vals', full_name='protoicp.Transform.vals', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=48,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='protoicp.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protoicp.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='protoicp.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='protoicp.Point.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=90,
)


_CLOUD = _descriptor.Descriptor(
  name='Cloud',
  full_name='protoicp.Cloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='protoicp.Cloud.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=132,
)


_OBJECTCLOUDS = _descriptor.Descriptor(
  name='ObjectClouds',
  full_name='protoicp.ObjectClouds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clouds', full_name='protoicp.ObjectClouds.clouds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=181,
)

_CLOUD.fields_by_name['points'].message_type = _POINT
_OBJECTCLOUDS.fields_by_name['clouds'].message_type = _CLOUD
DESCRIPTOR.message_types_by_name['Transform'] = _TRANSFORM
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Cloud'] = _CLOUD
DESCRIPTOR.message_types_by_name['ObjectClouds'] = _OBJECTCLOUDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transform = _reflection.GeneratedProtocolMessageType('Transform', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORM,
  '__module__' : 'icp_pb2'
  # @@protoc_insertion_point(class_scope:protoicp.Transform)
  })
_sym_db.RegisterMessage(Transform)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'icp_pb2'
  # @@protoc_insertion_point(class_scope:protoicp.Point)
  })
_sym_db.RegisterMessage(Point)

Cloud = _reflection.GeneratedProtocolMessageType('Cloud', (_message.Message,), {
  'DESCRIPTOR' : _CLOUD,
  '__module__' : 'icp_pb2'
  # @@protoc_insertion_point(class_scope:protoicp.Cloud)
  })
_sym_db.RegisterMessage(Cloud)

ObjectClouds = _reflection.GeneratedProtocolMessageType('ObjectClouds', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTCLOUDS,
  '__module__' : 'icp_pb2'
  # @@protoc_insertion_point(class_scope:protoicp.ObjectClouds)
  })
_sym_db.RegisterMessage(ObjectClouds)



_CALCTRANSFORM = _descriptor.ServiceDescriptor(
  name='CalcTransform',
  full_name='protoicp.CalcTransform',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=183,
  serialized_end=261,
  methods=[
  _descriptor.MethodDescriptor(
    name='getTransform',
    full_name='protoicp.CalcTransform.getTransform',
    index=0,
    containing_service=None,
    input_type=_OBJECTCLOUDS,
    output_type=_TRANSFORM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCTRANSFORM)

DESCRIPTOR.services_by_name['CalcTransform'] = _CALCTRANSFORM

# @@protoc_insertion_point(module_scope)
