# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import msg_pb2 as msg__pb2


class DetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detect_img = channel.unary_unary(
                '/protomsg.Detector/detect_img',
                request_serializer=msg__pb2.Image.SerializeToString,
                response_deserializer=msg__pb2.Detection.FromString,
                )


class DetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detect_img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detect_img': grpc.unary_unary_rpc_method_handler(
                    servicer.detect_img,
                    request_deserializer=msg__pb2.Image.FromString,
                    response_serializer=msg__pb2.Detection.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protomsg.Detector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Detector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detect_img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protomsg.Detector/detect_img',
            msg__pb2.Image.SerializeToString,
            msg__pb2.Detection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TesterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test_grpc = channel.unary_unary(
                '/protomsg.Tester/test_grpc',
                request_serializer=msg__pb2.TestMsg.SerializeToString,
                response_deserializer=msg__pb2.TestMsg.FromString,
                )


class TesterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test_grpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TesterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test_grpc': grpc.unary_unary_rpc_method_handler(
                    servicer.test_grpc,
                    request_deserializer=msg__pb2.TestMsg.FromString,
                    response_serializer=msg__pb2.TestMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protomsg.Tester', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tester(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test_grpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protomsg.Tester/test_grpc',
            msg__pb2.TestMsg.SerializeToString,
            msg__pb2.TestMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
