# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import icp_pb2 as icp__pb2


class CalcTransformStub(object):
    """Services define the different communication scenarios available
    A simple service for generating color
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTransform = channel.unary_unary(
                '/protoicp.CalcTransform/getTransform',
                request_serializer=icp__pb2.ObjectClouds.SerializeToString,
                response_deserializer=icp__pb2.Transform.FromString,
                )


class CalcTransformServicer(object):
    """Services define the different communication scenarios available
    A simple service for generating color
    """

    def getTransform(self, request, context):
        """Generates a random color on each request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalcTransformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransform,
                    request_deserializer=icp__pb2.ObjectClouds.FromString,
                    response_serializer=icp__pb2.Transform.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoicp.CalcTransform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalcTransform(object):
    """Services define the different communication scenarios available
    A simple service for generating color
    """

    @staticmethod
    def getTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoicp.CalcTransform/getTransform',
            icp__pb2.ObjectClouds.SerializeToString,
            icp__pb2.Transform.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
